// 合成規則數據
export const combos = [
    { group: "Bleed", ballA: "Bleed", ballB: "Vampire", result: "Vampire Lord" },
    { group: "Bleed", ballA: "Bleed", ballB: "Brood Mother", result: "Leech" },
    { group: "Bleed", ballA: "Bleed", ballB: "Poison", result: "Virus" },
    { group: "Bleed", ballA: "Bleed", ballB: "Charm", result: "Berserk" },
    { group: "Bleed", ballA: "Bleed", ballB: "Dark", result: "Sacrifice" },
    { group: "Bleed", ballA: "Bleed", ballB: "Iron", result: "Hemorrhage" },
    { group: "Brood Mother", ballA: "Brood Mother", ballB: "Bleed", result: "Leech" },
    { group: "Brood Mother", ballA: "Brood Mother", ballB: "Cell", result: "Maggot" },
    { group: "Brood Mother", ballA: "Brood Mother", ballB: "Egg Sac", result: "Spider Queen" },
    { group: "Brood Mother", ballA: "Brood Mother", ballB: "Vampire", result: "Mosquito King" },
    { group: "Burn", ballA: "Burn", ballB: "Iron", result: "Bomb" },
    { group: "Burn", ballA: "Burn", ballB: "Earthquake", result: "Magma" },
    { group: "Burn", ballA: "Burn", ballB: "Wind", result: "Inferno" },
    { group: "Burn", ballA: "Burn", ballB: "Charm", result: "Berserk" },
    { group: "Burn", ballA: "Burn", ballB: "Light", result: "Sun" },
    { group: "Burn", ballA: "Burn", ballB: "Freeze", result: "Frozen Flame" },
    { group: "Cell", ballA: "Cell", ballB: "Brood Mother", result: "Maggot" },
    { group: "Cell", ballA: "Cell", ballB: "Earthquake", result: "Overgrowth" },
    { group: "Cell", ballA: "Cell", ballB: "Laser", result: "Radiation Beam" },
    { group: "Cell", ballA: "Cell", ballB: "Egg Sac", result: "Voluptuous Egg Sac" },
    { group: "Cell", ballA: "Cell", ballB: "Poison", result: "Virus" },
    { group: "Charm", ballA: "Charm", ballB: "Vampire", result: "Succubus" },
    { group: "Charm", ballA: "Charm", ballB: "Bleed", result: "Berserk" },
    { group: "Charm", ballA: "Charm", ballB: "Dark", result: "Incubus" },
    { group: "Charm", ballA: "Charm", ballB: "Lightning", result: "Lovestruck" },
    { group: "Dark", ballA: "Dark", ballB: "Bleed", result: "Sacrifice" },
    { group: "Dark", ballA: "Dark", ballB: "Iron", result: "Assassin" },
    { group: "Dark", ballA: "Dark", ballB: "Ghost", result: "Phantom" },
    { group: "Dark", ballA: "Dark", ballB: "Vampire", result: "Vampire Lord" },
    { group: "Dark", ballA: "Dark", ballB: "Charm", result: "Incubus" },
    { group: "Dark", ballA: "Dark", ballB: "Sun", result: "Black Hole" },
    { group: "Dark", ballA: "Dark", ballB: "Wind", result: "Noxious" },
    { group: "Dark", ballA: "Dark", ballB: "Light", result: "Flicker" },
    { group: "Earthquake", ballA: "Earthquake", ballB: "Burn", result: "Magma" },
    { group: "Earthquake", ballA: "Earthquake", ballB: "Freeze", result: "Glacier" },
    { group: "Earthquake", ballA: "Earthquake", ballB: "Poison", result: "Swamp" },
    { group: "Earthquake", ballA: "Earthquake", ballB: "Wind", result: "Sandstorm" },
    { group: "Earthquake", ballA: "Earthquake", ballB: "Cell", result: "Overgrowth" },
    { group: "Egg Sac", ballA: "Egg Sac", ballB: "Brood Mother", result: "Spider Queen" },
    { group: "Egg Sac", ballA: "Egg Sac", ballB: "Iron", result: "Shotgun" },
    { group: "Egg Sac", ballA: "Egg Sac", ballB: "Vampire", result: "Mosquito Swarm" },
    { group: "Egg Sac", ballA: "Egg Sac", ballB: "Cell", result: "Voluptuous Egg Sac" },
    { group: "Freeze", ballA: "Freeze", ballB: "Ghost", result: "Wraith" },
    { group: "Freeze", ballA: "Freeze", ballB: "Laser", result: "Freeze Ray" },
    { group: "Freeze", ballB: "Wind", result: "Blizzard" },
    { group: "Freeze", ballA: "Freeze", ballB: "Earthquake", result: "Glacier" },
    { group: "Freeze", ballA: "Freeze", ballB: "Burn", result: "Frozen Flame" },
    { group: "Freeze", ballA: "Freeze", ballB: "Lightning", result: "Blizzard" },
    { group: "Ghost", ballA: "Ghost", ballB: "Dark", result: "Phantom" },
    { group: "Ghost", ballA: "Ghost", ballB: "Freeze", result: "Wraith" },
    { group: "Ghost", ballA: "Ghost", ballB: "Poison", result: "Virus" },
    { group: "Ghost", ballA: "Ghost", ballB: "Vampire", result: "Soul Sucker" },
    { group: "Ghost", ballA: "Ghost", ballB: "Iron", result: "Assassin" },
    { group: "Iron", ballA: "Iron", ballB: "Lightning", result: "Lightning Rod" },
    { group: "Iron", ballA: "Iron", ballB: "Dark", result: "Assassin" },
    { group: "Iron", ballA: "Iron", ballB: "Ghost", result: "Assassin" },
    { group: "Iron", ballA: "Iron", ballB: "Burn", result: "Bomb" },
    { group: "Iron", ballA: "Iron", ballB: "Bleed", result: "Hemorrhage" },
    { group: "Iron", ballA: "Iron", ballB: "Egg Sac", result: "Shotgun" },
    { group: "Laser", ballA: "Laser", ballB: "Laser", result: "Holy Laser" },
    { group: "Laser", ballA: "Laser", ballB: "Freeze", result: "Freeze Ray" },
    { group: "Laser", ballA: "Laser", ballB: "Poison", result: "Radiation Beam" },
    { group: "Laser", ballA: "Laser", ballB: "Cell", result: "Radiation Beam" },
    { group: "Laser", ballA: "Laser", ballB: "Light", result: "Laser Beam" },
    { group: "Light", ballA: "Light", ballB: "Burn", result: "Sun" },
    { group: "Light", ballA: "Light", ballB: "Dark", result: "Flicker" },
    { group: "Light", ballA: "Light", ballB: "Laser", result: "Laser Beam" },
    { group: "Light", ballA: "Light", ballB: "Charm", result: "Lovestruck" },
    { group: "Lightning", ballA: "Lightning", ballB: "Iron", result: "Lightning Rod" },
    { group: "Lightning", ballB: "Wind", result: "Storm" },
    { group: "Lightning", ballA: "Lightning", ballB: "Freeze", result: "Blizzard" },
    { group: "Lightning", ballA: "Lightning", ballB: "Light", result: "Flash" },
    { group: "Lightning", ballA: "Lightning", ballB: "Charm", result: "Lovestruck" },
    { group: "Poison", ballA: "Poison", ballB: "Laser", result: "Radiation Beam" },
    { group: "Poison", ballA: "Poison", ballB: "Earthquake", result: "Swamp" },
    { group: "Poison", ballA: "Poison", ballB: "Wind", result: "Noxious" },
    { group: "Poison", ballA: "Poison", ballB: "Bomb", result: "Nuclear Bomb" },
    { group: "Poison", ballA: "Poison", ballB: "Ghost", result: "Virus" },
    { group: "Vampire", ballA: "Vampire", ballB: "Bleed", result: "Vampire Lord" },
    { group: "Vampire", ballA: "Vampire", ballB: "Brood Mother", result: "Mosquito King" },
    { group: "Vampire", ballA: "Vampire", ballB: "Egg Sac", result: "Mosquito Swarm" },
    { group: "Vampire", ballA: "Vampire", ballB: "Ghost", result: "Soul Sucker" },
    { group: "Vampire", ballA: "Vampire", ballB: "Dark", result: "Vampire Lord" },
    { group: "Vampire", ballA: "Vampire", ballB: "Charm", result: "Succubus" },
    { group: "Wind", ballA: "Wind", ballB: "Lightning", result: "Storm" },
    { group: "Wind", ballA: "Wind", ballB: "Earthquake", result: "Sandstorm" },
    { group: "Wind", ballA: "Wind", ballB: "Dark", result: "Noxious" },
    { group: "Wind", ballA: "Wind", ballB: "Freeze", result: "Blizzard" },
    { group: "Wind", ballA: "Wind", ballB: "Burn", result: "Inferno" },
    { group: "Wind", ballA: "Wind", ballB: "Poison", result: "Noxious" },
    { group: "Other", ballA: "Incubus", ballB: "Succubus", result: "Satan" },
    { group: "Other", ballA: "Vampire Lord", ballB: "Mosquito King", ballB2: "Spider Queen", result: "Nosferatu" }
];

// 被動合成數據
export const passivesCombos = [
    { passiveA: "Rattle", passiveB: "War Horn", result: "Cornucopia" },
    { passiveA: "Spear", passiveB: "Bullseye Amulet", result: "Elegant Rapier" },
    { passiveA: "Onion", passiveB: "Breastplate", result: "Odiferous Shell" },
    { passiveA: "Ghost Girdle", passiveB: "Phantom Cloak", result: "Phantom Regalia" },
    { passiveA: "Bottomless Chalice", passiveB: "Vampire Sword", result: "Soul Reaver" },
    { passiveA: "Crown of Thorns", passiveB: "Spike Collar", result: "Tormenters Mask" },
    { passiveA: "Fleet Feet", passiveB: "Radiant Feathers", result: "Wings of the Anointed" },
    { passiveA: "Red Dagger", passiveB: "Blue Dagger", passiveB2: "Green Dagger", passiveB3: "Emerald Dagger", result: "Deadeye's Cross" },
    { passiveA: "Spear", passiveB: "Bullseye Amulet", result: "Gracious Impaler" }
];